package theads;

public class ResultTask extends Thread {
    public void run() {
        System.out.println("result generated by:" + Thread.currentThread().getName());
    }

    public static void main(String[] args) {
        ResultTask t1 = new ResultTask();
        t1.run();
        t1.start();

    }

//start() internally calls run()
// //Thraed cannot be started twice
}
